version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: julia
    directories:
      - /
      - /docs
      - /test
      - /test/code-quality
      - /examples
    schedule:
      interval: weekly
